version: 1.1.{build}
environment:
  developmentversion: {version}-beta
init:
- ps: "Write-Host $env:version\nWrite-Host $env:developmentversion\nif ($env:APPVEYOR_REPO_BRANCH -ieq \"development\")\n{\n Set-AppveyorBuildVariable 'version' '$env:developmentversion' \n}"
branches:
  only:
  - master
  - Development  
skip_tags: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache: src\packages
nuget:
  project_feed: true
build:
  project: src\MediatR.sln
  verbosity: minimal
after_build:
- ps: ".\\src\\.nuget\\NuGet.exe pack \"src\\Portable.MediatR\\Portable.MediatR.csproj\" -Prop \"Configuration=$env:CONFIGURATION;Platform=AnyCPU\" -OutputDirectory $env:APPVEYOR_BUILD_FOLDER -Verbosity detailed -Build\nif ($env:APPVEYOR_REPO_BRANCH -ieq \"development\")\n{\n  Get-ChildItem Portable.MediatR*.nupkg | select -f 1 | Rename-Item -NewName {$_.Name -replace '.nupkg','-beta.nupkg'}\n}"
test_script:
- vstest.console /logger:Appveyor /TestAdapterPath:"%APPVEYOR_BUILD_FOLDER%\src\packages\Fixie.1.0.0.1\lib\net45" "%APPVEYOR_BUILD_FOLDER%\src\MediatR.Tests\bin\Release\MediatR.Tests.dll"
artifacts:
- path: Portable.MediatR*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: YPGdPLnY9FEYDZz3zZFV/+BKreynP4W2/DoURr0XlBjS8eLkkSypvEkI0BQSfRur
  artifact: /Portable.MediatR.*\.nupkg/
  on:
    branch: /master|Development/